#Install and configure Nginx
- name: Check or install Nginx
  apt: name=nginx state=present update_cache=yes
  become: yes

- name: Check that lets encrypt is installed
  apt: name=letsencrypt state=present update_cache=yes
  become: yes

- name: custom Nginx configuration
  template: src=nginx_conf.j2 dest=/etc/nginx/conf.d/app.conf
  become: yes

- name: Create letsencrypt directory
  file: name=/var/www/letsencrypt state=directory
  become: yes

- name: Remove default landing page
  file: name=/etc/nginx/sites-enabled/default state=absent
  become: yes

- name: Check if cert already exists
  stat:
    path: "/etc/letsencrypt/live/{{domain name}}"
  register: certs # registers a variable called certs
  become: yes

- name: Wait for letsencrypt cert
  service:
    name: nginx
    state: stopped
  become: yes
  when: not certs.stat.exists

- name: Create cert with lets encrypt
  shell: "letsencrypt certonly --standalone -d {{domain_name}} -w {{webserver_dir}} -m {{email_for_ssl_cert}} --agree-tos --renew-by-default --non-interactive"
  become: yes
  when: not certs.stat.exists #uses the registered variable from the task above, basically if statement

- name: Generate Diffie-Hellman group
  shell: "openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048"
  become: yes
  when: not certs.stat.exists

- name: Start nginx after letsencrypt cert present
  service:
    name: ngnix
    state: started
  become: yes


