#Install and configure Nginx
- name: Check or install Nginx
  apt: name=nginx state=present update_cache=yes
  become: yes

- name: custom Nginx configuration
  template: src=nginx_conf.j2 dest=/etc/nginx/conf.d/app.conf
  become: yes
